# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_tools.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10grpc_tools.proto\x12\nmafia_game\"\x07\n\x05\x45mpty\"\x1d\n\x08PlayerId\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\"!\n\nPlayerName\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\"L\n\rSessionPlayer\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x13\n\x0bplayer_name\x18\x02 \x01(\t\x12\x13\n\x0bplayer_role\x18\x03 \x01(\t\"]\n\x0bSessionInfo\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0e\n\x06is_day\x18\x02 \x01(\x08\x12*\n\x07players\x18\x03 \x03(\x0b\x32\x19.mafia_game.SessionPlayer\"D\n\x06Player\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x12\n\nsession_id\x18\x02 \x01(\x05\x12\x13\n\x0bplayer_name\x18\x03 \x01(\t\"5\n\nPlayerList\x12\'\n\x0b\x61ll_players\x18\x01 \x03(\x0b\x32\x12.mafia_game.Player\"2\n\rActionRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"$\n\x0e\x41\x63tionResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\"\x1a\n\x07\x41\x63tions\x12\x0f\n\x07\x61\x63tions\x18\x01 \x03(\t2\x9c\x03\n\tMafiaGame\x12\x41\n\x0fOnClientConnect\x12\x16.mafia_game.PlayerName\x1a\x14.mafia_game.PlayerId\"\x00\x12I\n\x0eOnClientAction\x12\x19.mafia_game.ActionRequest\x1a\x1a.mafia_game.ActionResponse\"\x00\x12@\n\x11OnClientHeartbeat\x12\x14.mafia_game.PlayerId\x1a\x13.mafia_game.Actions\"\x00\x12<\n\rGetAllPlayers\x12\x11.mafia_game.Empty\x1a\x16.mafia_game.PlayerList\"\x00\x12>\n\x0fGetValidActions\x12\x14.mafia_game.PlayerId\x1a\x13.mafia_game.Actions\"\x00\x12\x41\n\x0eGetSessionInfo\x12\x14.mafia_game.PlayerId\x1a\x17.mafia_game.SessionInfo\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_tools_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=32
  _EMPTY._serialized_end=39
  _PLAYERID._serialized_start=41
  _PLAYERID._serialized_end=70
  _PLAYERNAME._serialized_start=72
  _PLAYERNAME._serialized_end=105
  _SESSIONPLAYER._serialized_start=107
  _SESSIONPLAYER._serialized_end=183
  _SESSIONINFO._serialized_start=185
  _SESSIONINFO._serialized_end=278
  _PLAYER._serialized_start=280
  _PLAYER._serialized_end=348
  _PLAYERLIST._serialized_start=350
  _PLAYERLIST._serialized_end=403
  _ACTIONREQUEST._serialized_start=405
  _ACTIONREQUEST._serialized_end=455
  _ACTIONRESPONSE._serialized_start=457
  _ACTIONRESPONSE._serialized_end=493
  _ACTIONS._serialized_start=495
  _ACTIONS._serialized_end=521
  _MAFIAGAME._serialized_start=524
  _MAFIAGAME._serialized_end=936
# @@protoc_insertion_point(module_scope)
